# DigitalOcean App Platform Configuration
# Use this file to deploy via DigitalOcean App Platform

name: kaamkart
region: nyc

# Backend API Service
services:
  - name: api
    github:
      repo: your-username/nokariya
      branch: main
      deploy_on_push: true
    source_dir: kaamkartApi
    build_command: mvn clean package -DskipTests
    run_command: java -jar -Dspring.profiles.active=prod target/kaamkart-api-1.0.0.jar
    environment_slug: java
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8585
    routes:
      - path: /
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: DB_USERNAME
        value: ${db.DATABASE_USER}
        type: SECRET
      - key: DB_PASSWORD
        value: ${db.DATABASE_PASSWORD}
        type: SECRET
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET
      - key: CORS_ALLOWED_ORIGINS
        value: https://kaamkart.in,https://www.kaamkart.in
      - key: WEBSOCKET_ALLOWED_ORIGINS
        value: https://kaamkart.in,https://www.kaamkart.in
      - key: SERVER_PORT
        value: "8585"
    health_check:
      http_path: /api/health

# Frontend Static Site
static_sites:
  - name: ui
    github:
      repo: your-username/nokariya
      branch: main
      deploy_on_push: true
    source_dir: kaamkartUI
    build_command: npm ci && npm run build
    output_dir: .next
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.kaamkart.in/api
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://api.kaamkart.in

# Database
databases:
  - name: db
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: kaamkart-db

# Alerts
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
  - rule: MEM_UTILIZATION
    disabled: false
  - rule: RESTART_COUNT
    disabled: false
  - rule: DEPLOYMENT_FAILED
    disabled: false

